---
 - name: host website inside container
   hosts: node1
   tasks:
     - name: install docker
       yum:
         name: docker
         state: present
     - name: start enable docker
       service:
         name: docker
         state: started
         enabled: yes
     - name: create httpd container with default page
       shell: docker run -dt --name=c1 -t -p 81:80 httpd 